<div class="{__NODE_ID__} {TYPE_CLASS}">

    {ENABLED_TOGGLE_BUTTON}
    <!-- combine_mode -->
    {SET_BUTTON}
    <!-- / -->
    {REQUIRED_TOGGLE_BUTTON}
    {CACHE_OUTPUT_TOGGLE_BUTTON}
    {CREATE_HANDLER_BUTTON}
    {CREATE_VALUE_BUTTON}
    {ADD_GLOBAL_BUTTON}
    {SAVE_AS_GLOBAL_BUTTON}
    {USE_GLOBAL_BUTTON}
    {USE_LOCAL_BUTTON}
    {EXCHANGE_BUTTON}
    {COPY_BUTTON}
    {PASTE_BUTTON}
    {DELETE_BUTTON}

    <div class="cb"></div>

</div>
