<div class="{__NODE_ID__}">

    {ENABLED_TOGGLE_BUTTON}
    {REQUIRED_TOGGLE_BUTTON}
    {CACHE_OUTPUT_TOGGLE_BUTTON}
    {CREATE_VAR_BUTTON}
    {CREATE_INPUT_BUTTON}
    {SAVE_AS_GLOBAL_BUTTON}
    {USE_GLOBAL_BUTTON}
    {USE_LOCAL_BUTTON}
    {EXCHANGE_BUTTON}
    {COPY_BUTTON}
    {PASTE_BUTTON}
    {DELETE_BUTTON}

    <div class="cb"></div>

</div>
